"""agrega vehiculos depositos clientes rutas paradas pod incidencias

Revision ID: 31fd833e3446
Revises: 3a07a2628ffc
Create Date: 2026-08-26 09:17:57.298525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31fd833e3446'
down_revision: Union[str, Sequence[str], None] = '3a07a2628ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('demanda_carga_default', sa.Integer(), nullable=True),
    sa.Column('tiempo_servicio_default', sa.Integer(), nullable=False),
    sa.Column('ventana_inicio_default', sa.Integer(), nullable=True),
    sa.Column('ventana_fin_default', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_clientes_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_clientes_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes'))
    )
    op.create_table('depositos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('ventana_inicio', sa.Integer(), nullable=True),
    sa.Column('ventana_fin', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_depositos_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_depositos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_depositos'))
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('tipo_vehiculo', sa.Enum('MOTO', 'AUTO', 'CAMIONETA', 'FURGON', 'CAMION', name='tipo_vehiculo', native_enum=False), nullable=False),
    sa.Column('patente', sa.String(length=12), nullable=False),
    sa.Column('capacidad_carga_kg', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_vehiculos_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_vehiculos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehiculos')),
    sa.UniqueConstraint('patente', name=op.f('uq_vehiculos_patente'))
    )
    # Migración de datos: los choferes que ya tenían tipo_vehiculo/patente/
    # capacidad_carga_kg cargados en usuarios pasan a tener su Vehiculo propio
    # antes de que esas columnas se borren más abajo.
    op.execute("""
        INSERT INTO vehiculos (id, empresa_id, usuario_id, tipo_vehiculo, patente, capacidad_carga_kg, activo, fecha_creacion)
        SELECT gen_random_uuid(), empresa_id, id, tipo_vehiculo, patente, capacidad_carga_kg, true, now()
        FROM usuarios
        WHERE tipo_vehiculo IS NOT NULL
    """)
    op.create_table('rutas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chofer_id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=False),
    sa.Column('deposito_id', sa.UUID(), nullable=False),
    sa.Column('creado_por_usuario_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_problema', sa.Enum('CVRP', 'VRPTW', name='tipo_problema', native_enum=False), nullable=False),
    sa.Column('estado', sa.Enum('PLANIFICADA', 'EN_CURSO', 'COMPLETADA', 'CANCELADA', name='estado_ruta', native_enum=False), nullable=False),
    sa.Column('distancia_total_m', sa.Integer(), nullable=True),
    sa.Column('tiempo_total_min', sa.Integer(), nullable=True),
    sa.Column('hora_inicio_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_fin_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chofer_id'], ['usuarios.id'], name=op.f('fk_rutas_chofer_id_usuarios')),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], name=op.f('fk_rutas_creado_por_usuario_id_usuarios')),
    sa.ForeignKeyConstraint(['deposito_id'], ['depositos.id'], name=op.f('fk_rutas_deposito_id_depositos')),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], name=op.f('fk_rutas_vehiculo_id_vehiculos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rutas'))
    )
    op.create_table('paradas_ruta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ruta_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_CURSO', 'COMPLETADA', 'FALLIDA', name='estado_parada', native_enum=False), nullable=False),
    sa.Column('nombre_snapshot', sa.String(length=200), nullable=False),
    sa.Column('direccion_snapshot', sa.String(length=300), nullable=False),
    sa.Column('latitud_snapshot', sa.Float(), nullable=False),
    sa.Column('longitud_snapshot', sa.Float(), nullable=False),
    sa.Column('demanda_carga_snapshot', sa.Integer(), nullable=False),
    sa.Column('tiempo_servicio_snapshot', sa.Integer(), nullable=False),
    sa.Column('ventana_inicio_snapshot', sa.Integer(), nullable=True),
    sa.Column('ventana_fin_snapshot', sa.Integer(), nullable=True),
    sa.Column('hora_estimada_llegada', sa.Integer(), nullable=True),
    sa.Column('hora_real_llegada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_real_salida', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_paradas_ruta_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], name=op.f('fk_paradas_ruta_ruta_id_rutas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paradas_ruta')),
    sa.UniqueConstraint('ruta_id', 'orden', name=op.f('uq_paradas_ruta_ruta_id'))
    )
    op.create_table('incidencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ruta_id', sa.UUID(), nullable=False),
    sa.Column('parada_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('CLIENTE_AUSENTE', 'RECHAZO_ENTREGA', 'DIRECCION_INCORRECTA', 'MERCADERIA_DANADA', 'PROBLEMA_VEHICULO', 'OTRO', name='tipo_incidencia', native_enum=False), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('reportado_por_usuario_id', sa.UUID(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parada_id'], ['paradas_ruta.id'], name=op.f('fk_incidencias_parada_id_paradas_ruta')),
    sa.ForeignKeyConstraint(['reportado_por_usuario_id'], ['usuarios.id'], name=op.f('fk_incidencias_reportado_por_usuario_id_usuarios')),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], name=op.f('fk_incidencias_ruta_id_rutas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidencias'))
    )
    op.create_table('pruebas_entrega',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parada_id', sa.UUID(), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('firma_url', sa.String(length=500), nullable=True),
    sa.Column('nombre_receptor', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parada_id'], ['paradas_ruta.id'], name=op.f('fk_pruebas_entrega_parada_id_paradas_ruta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pruebas_entrega')),
    sa.UniqueConstraint('parada_id', name=op.f('uq_pruebas_entrega_parada_id'))
    )
    op.drop_column('usuarios', 'tipo_vehiculo')
    op.drop_column('usuarios', 'patente')
    op.drop_column('usuarios', 'capacidad_carga_kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('capacidad_carga_kg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('patente', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('tipo_vehiculo', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    # Restaura los datos de vehículo en usuarios antes de borrar la tabla nueva.
    op.execute("""
        UPDATE usuarios u
        SET tipo_vehiculo = v.tipo_vehiculo, patente = v.patente, capacidad_carga_kg = v.capacidad_carga_kg
        FROM vehiculos v
        WHERE v.usuario_id = u.id
    """)
    op.drop_table('pruebas_entrega')
    op.drop_table('incidencias')
    op.drop_table('paradas_ruta')
    op.drop_table('rutas')
    op.drop_table('vehiculos')
    op.drop_table('depositos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
