"""agrega datos de vehiculo al chofer

Revision ID: 3a07a2628ffc
Revises: f26f42694fa1
Create Date: 2026-08-24 18:35:59.881504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a07a2628ffc'
down_revision: Union[str, Sequence[str], None] = 'f26f42694fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=30), nullable=True))
    op.add_column('usuarios', sa.Column('tipo_vehiculo', sa.Enum('MOTO', 'AUTO', 'CAMIONETA', 'FURGON', 'CAMION', name='tipo_vehiculo', native_enum=False), nullable=True))
    op.add_column('usuarios', sa.Column('patente', sa.String(length=12), nullable=True))
    op.add_column('usuarios', sa.Column('capacidad_carga_kg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'capacidad_carga_kg')
    op.drop_column('usuarios', 'patente')
    op.drop_column('usuarios', 'tipo_vehiculo')
    op.drop_column('usuarios', 'telefono')
    # ### end Alembic commands ###
