"""agrega explicacion a rutas

Revision ID: 6b1aaa89e783
Revises: 31fd833e3446
Create Date: 2026-08-27 11:09:18.585334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1aaa89e783'
down_revision: Union[str, Sequence[str], None] = '31fd833e3446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rutas', sa.Column('explicacion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rutas', 'explicacion')
    # ### end Alembic commands ###
