"""crear tablas empresas usuarios codigos_invitacion

Revision ID: f26f42694fa1
Revises: 
Create Date: 2026-08-24 12:21:25.093684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26f42694fa1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.Enum('PRUEBA', 'BASICO', 'PREMIUM', name='plan_suscripcion', native_enum=False), nullable=False),
    sa.Column('fecha_fin_prueba', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('CHOFER', 'ADMIN', name='rol_usuario', native_enum=False), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('plan', sa.Enum('PRUEBA', 'BASICO', 'PREMIUM', name='plan_suscripcion', native_enum=False), nullable=False),
    sa.Column('fecha_fin_prueba', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_usuarios_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('codigos_invitacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=12), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('creado_por_usuario_id', sa.UUID(), nullable=False),
    sa.Column('usado_por_usuario_id', sa.UUID(), nullable=True),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_uso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], name=op.f('fk_codigos_invitacion_creado_por_usuario_id_usuarios')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_codigos_invitacion_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['usado_por_usuario_id'], ['usuarios.id'], name=op.f('fk_codigos_invitacion_usado_por_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_codigos_invitacion'))
    )
    op.create_index(op.f('ix_codigos_invitacion_codigo'), 'codigos_invitacion', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codigos_invitacion_codigo'), table_name='codigos_invitacion')
    op.drop_table('codigos_invitacion')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('empresas')
    # ### end Alembic commands ###
