"""agrega bultos, distancia acumulada y cierre estimado a rutas

Revision ID: f716e6721aa3
Revises: 6b1aaa89e783
Create Date: 2026-08-31 12:32:35.745252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f716e6721aa3'
down_revision: Union[str, Sequence[str], None] = '6b1aaa89e783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='0' para no romper filas existentes (paradas_ruta ya
    # tiene datos de rutas confirmadas antes de esta migración) — el default
    # de SQLAlchemy en db/modelos.py es a nivel de aplicación, no de columna.
    op.add_column(
        'paradas_ruta',
        sa.Column('unidades_snapshot', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'paradas_ruta',
        sa.Column('distancia_acumulada_m', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('rutas', sa.Column('hora_fin_estimada_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rutas', 'hora_fin_estimada_min')
    op.drop_column('paradas_ruta', 'distancia_acumulada_m')
    op.drop_column('paradas_ruta', 'unidades_snapshot')
    # ### end Alembic commands ###
